[package]
name = "png-to-terminal"
version = "0.1.1"
edition = "2021"
description = "Render PNG images directly in the terminal using TrueColor"
license = "MIT"
repository = "https://github.com/tuna4ll/png-to-terminal"
readme = "README.md"

[dependencies]
image = "0.24"
